# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('video_code', models.CharField(blank=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('script', 'Script'), ('shooting', 'Shooting'), ('editing', 'Editing'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('owner_review', 'Owner Review'), ('posted', 'Posted')], db_index=True, default='idea', max_length=30)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('script', 'Script'), ('shooting', 'Shooting'), ('editing', 'Editing'), ('internal_review', 'Internal Review'), ('client_review', 'Client Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('owner_review', 'Owner Review'), ('posted', 'Posted')], db_index=True, default='idea', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('script', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('edit_due_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('raw_footage_urls', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list)),
                ('edited_video_url', models.URLField(blank=True)),
                ('final_video_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('instagram_caption', models.TextField(blank=True)),
                ('instagram_hashtags', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list)),
                ('instagram_post_url', models.URLField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_videos', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_videos', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_videos', to=settings.AUTH_USER_MODEL)),
                ('monthly_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='targets.monthlytarget')),
                ('shooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_videos', to=settings.AUTH_USER_MODEL)),
                ('social_media_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zf_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], default='instagram', max_length=40)),
                ('post_type', models.CharField(default='feed', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list)),
                ('mention_users', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_posts', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='videos.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('file_url', models.CharField(max_length=500)),
                ('kind', models.CharField(default='file', max_length=40)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_uploads', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['client'], name='zf_videos_client__034012_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['assigned_to'], name='zf_videos_assigne_22625e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['stage'], name='zf_videos_stage_38855a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='zf_videos_status_f3532c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['deadline'], name='zf_videos_deadlin_be1fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='zf_videos_created_2ddd71_idx'),
        ),
    ]
