# Generated by Django 5.2.17 on 2026-09-17 08:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('notification_type', models.CharField(default='info', max_length=60)),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=60)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zf_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
