# Generated by Django 5.2.17 on 2026-09-17 08:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('content_type', models.CharField(default='video', max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('approval_type', models.CharField(default='internal', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='pending', max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_contact', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('change_requests', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'zf_approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
