# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('tasks', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='approval',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='videos.video'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status'], name='zf_approval_status_0d528c_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['requested_by'], name='zf_approval_request_019fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['reviewed_by'], name='zf_approval_reviewe_49f6be_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['created_at'], name='zf_approval_created_7cc9c5_idx'),
        ),
    ]
