# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('videos_target', 'Videos'), ('posts_target', 'Posts'), ('reels_target', 'Reels'), ('seo_target', 'SEO'), ('tasks_target', 'Tasks'), ('leads_target', 'Leads')], default='videos_target', max_length=40)),
                ('target_value', models.PositiveIntegerField(default=0)),
                ('achieved_value', models.PositiveIntegerField(default=0)),
                ('target_videos', models.PositiveIntegerField(default=0)),
                ('completed_videos', models.PositiveIntegerField(default=0)),
                ('posted_videos', models.PositiveIntegerField(default=0)),
                ('pending_videos', models.PositiveIntegerField(default=0)),
                ('in_production_videos', models.PositiveIntegerField(default=0)),
                ('waiting_approval_videos', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to='clients.client')),
            ],
            options={
                'db_table': 'zf_monthly_targets',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
