# Generated by Django 5.2.17 on 2026-09-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_alter_department_table'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytarget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_targets', to='departments.department'),
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monthlytarget',
            index=models.Index(fields=['year', 'month'], name='zf_monthly__year_43819e_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytarget',
            index=models.Index(fields=['user', 'year', 'month', 'target_type'], name='zf_monthly__user_id_84f3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytarget',
            index=models.Index(fields=['client', 'year', 'month', 'target_type'], name='zf_monthly__client__99d3a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytarget',
            unique_together={('user', 'department', 'client', 'month', 'year', 'target_type')},
        ),
    ]
