# Generated by Django 5.2.17 on 2026-09-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='zf_departments',
        ),
    ]
