# Generated by Django 5.2.17 on 2026-09-17 08:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('original_due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('carry_forward_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('attachments', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list)),
                ('estimated_hours', models.FloatField(default=0)),
                ('actual_hours', models.FloatField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('task_type', models.CharField(blank=True, default='general', max_length=80)),
            ],
            options={
                'db_table': 'zf_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'zf_task_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
