# Generated by Django 5.2.17 on 2026-09-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_task_completion_fields'),
        ('video_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='video_protocol.videostage'),
        ),
    ]
