# Generated by Django 5.2.17 on 2026-09-17 08:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('instagram_username', models.CharField(blank=True, max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived'), ('inactive', 'Inactive')], db_index=True, default='lead', max_length=20)),
                ('assigned_team_ids', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zf_clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
