# Generated by Django 5.2.17 on 2026-09-18 19:15

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_remove_client_zf_clients_status_901393_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVideoProtocol',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('target_videos', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_protocols', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protocols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zf_video_protocols',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('video_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_protocol.monthlyvideoprotocol')),
            ],
            options={
                'db_table': 'zf_video_records',
                'ordering': ['video_number'],
                'unique_together': {('protocol', 'video_number')},
            },
        ),
        migrations.CreateModel(
            name='VideoStage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('stage_type', models.CharField(choices=[('shoot', 'Shoot Video'), ('edit', 'Edit Video'), ('review', 'Review Video'), ('client_approval', 'Client Approval'), ('instagram_post', 'Instagram Post')], max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_stages', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='video_protocol.videorecord')),
            ],
            options={
                'db_table': 'zf_video_stages',
                'ordering': ['stage_type'],
                'unique_together': {('video', 'stage_type')},
            },
        ),
    ]
