# Generated by Django 5.2.17 on 2026-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostage',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videostage',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
