# Generated by Django 5.2.17 on 2026-09-17 08:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('STATUS_CHANGE', 'Status Change'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('ROLE_CHANGE', 'Role Change'), ('PASSWORD_CHANGE', 'Password Change'), ('CARRY_FORWARD', 'Carry Forward')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'zf_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
